[Android] - Add file type support and update core to 7.0.2 SDK-4096
CleverTap/clevertap-react-native pull request #429
Opened 2024-10-18 11:23 UTC by piyush-kukadiya

- [ ] Add `CleverTap.defineFileVariable("fileVariable")`
- [ ] Add `CleverTap.onOneTimeVariablesChanged(handler)`
- [ ] Add `CleverTap.onVariablesChangedAndNoDownloadsPending(handler)`
- [ ] Add `CleverTap.onceVariablesChangedAndNoDownloadsPending(handler)`
- [ ] Add `CleverTap.onFileValueChanged('fileVariable', handler)`
- [ ] Support core SDK `7.0.2`
- [ ] Update [Variables.md](https://github.com/CleverTap/clevertap-react-native/blob/master/docs/Variables.md)
- [ ] Update [ChangeLog.md](https://github.com/CleverTap/clevertap-react-native/blob/master/CHANGELOG.md)
- [ ] Update Example App
- [ ] Bump lib version to `3.1.0`

2024-10-21 05:09 UTC, kushCT approved these changes

2024-10-21 06:10 UTC, kushCT commented
@piyush-kukadiya I have pushed the changes from iOS which can be directly merged into develop branch from here. We don't need to merge the changes back to it's parent branch.

2024-10-21 06:38 UTC, Anush-Shand commented on src/index.js
> +        defineFileVariable: function (fileVariable) {
Formatting is a little off here

2024-10-21 16:14 UTC, nzagorchev requested changes
Looks good, dev tested it quickly on iOS. A few tiny changes requested.

2024-10-22 11:03 UTC, kushCT commented on src/index.js
> +        defineFileVariable: function (fileVariable) {
Resolved

2024-10-22 11:04 UTC, kushCT commented on ios/CleverTapReact/CleverTapReact.mm
> +    [[self cleverTapInstance]onceVariablesChangedAndNoDownloadsPending:^{
Resolved

2024-10-22 11:04 UTC, kushCT commented on ios/CleverTapReact/CleverTapReact.mm
> +    CTVar *fileVar = [[self cleverTapInstance]defineFileVar:fileVariable];
Resolved

2024-10-22 11:04 UTC, kushCT commented on Example/app/App.js
> +      CleverTap.onFileValueChanged('pk.fileVariable', (variable) => {
Resolved

2024-10-22 11:04 UTC, kushCT commented on Example/app/App.js
> +        CleverTap.onValueChanged('pk.fileVariable', (variable) => {
Resolved

2024-10-22 14:43 UTC, merged